# --- ZMK STUDIO YETKİLENDİRMESİ ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# --- BLUETOOTH VE MAC M4 UYUMLULUĞU ---
# Mac cihazlarla yaşanan eşleşme/kopma sorunlarını çözen deneysel protokol
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# --- SAĞ-SOL MODÜL GÜÇLENDİRMESİ ---
# Sağ ve Sol klavye arasındaki Bluetooth sinyal gücünü maksimuma (+8dBm) çıkarır
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- BATARYA GÖSTERGESİ ---
# İşletim sistemine batarya yüzdesini gönderir
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
